### ISSUE TITLE
Fallback to the latest version of a branch

### ISSUE THREAD

**Issue by Fenntasy** [howtowhale/dvm#139]
`dvm use 1.10` now just cause an error because the version number is not found.

It would be quite handy to just fallback on the last version of the 1.10 branch.

Or maybe something along the lines of `dvm use 1.10.latest` or `dvm use 1.10.x`.

**Comment by carolynvs** [comment]
Can you help me understand the use case better? I am assuming that this is related to #138, where it sounds like you don't have a good way of knowing what client version to specify in `dvm use`.

**Comment by Fenntasy** [comment]
Yes, that's related.

As I understand [this](https://docs.docker.com/engine/reference/api/docker_remote_api/), the client API version are related to minor releases of docker (that is to say, client API 1.22 is linked to the 1.10.x versions of docker for instance).

But still, it's not yet the case the list of versions is too big to be simply managed but it could happen in the future. You may want to be on the last version of a particular minor branch without having to look through the whole list of versions (and that could be a simple way to update if needed).

**Comment by carolynvs** [comment]
Is the goal to always use the latest docker client, e.g. 1.10.*, or do you want to match the host version? e.g. if the host has 1.10.1, do you also want 1.10.1 on the client, or do you want the latest compatible client?

Essentially I'm trying to figure out what info the user has, how did they get it and what they really wanted to happen from the start without all this trouble. 😄 

I can guess at least two scenarios but I'm not sure if this is what you are running into:

**Halp, I forgot the version**
 The user has a docker host _somewhere_ that was setup months ago and now they don't remember which docker version it has (and they aren't using Carina which provides `$DOCKER_VERSION`).

1. Just try to use docker and see if it works or not.
2. Oops, it didn't work and the error message says that the server is using API version 1.19
3. Err, I have no clue what I should put into the `dvm use` command...
4. Either find that webpage manually mapping the versions, or just play guess and check until they get it right.

What the user really wanted was `dvm detect` which would hit the docker api (`/version`) figure out what version their host is using, and update them to the right version of docker transparently.

**Bleeding Edge**
In this scenario, the user knows which version of docker the host is using, e.g. 1.11.1 but they always want to be using the latest client version. So instead of saying `dvm use 1.11.1` they want a command like `dvm use 1.11.*` and dvm will update them to the latest compatible version of docker.

After writing this out, both scenarios seem like good things to support. Is either of these what you were looking for?

**Comment by Fenntasy** [comment]
For my current usage, the first situation you described is exactly my case :)

**Comment by carolynvs** [comment]
I was hoping you'd say that!  `dvm detect` it is!

**Comment by carolynvs** [comment]
Seems now that we have `dvm detect`, this isn't needed.
